(define (call-with-input-file file proc)
  (let ((port (open-input-file file)))
    (proc port)
    (close-port port)))
(define (call-with-output-file file proc)
  (let ((port (open-output-file file)))
    (proc port)
    (close-port port)))
(define (with-input-from-file file thunk)
  (let ((port (open-input-file file))
        (old (current-input-file)))
    (dynamic-wind (lambda () (set-current-input-port! port))
                  (lambda () (proc port) (close-port port))
                  (lambda () (set-current-input-port! old)))))
(define (with-output-to-file file thunk)
  (let ((port (open-output-file file))
        (old (current-output-file)))
    (dynamic-wind (lambda () (set-current-output-port! port))
                  (lambda () (proc port) (close-port port))
                  (lambda () (set-current-output-port! old)))))