(import (scheme base))
(define (scheme->java x)
        (cond ((boolean? x) (boolean->Boolean x))
              ((string? x) (string->String x))
              ((symbol? x) (symbol->String x))
              ((bytevector? x) (bytevector->ByteArray x))
              ((integer? x) (integer->Integer x))
              ((real? x) (real->Double x))
              (else x)))
(define (java->scheme x)
        (cond ((instanceof x 'java.lang.Boolean) (Boolean->boolean x))
              ((instanceof x 'java.lang.String) (String->string x))
              ((instanceof x 'java.lang.Double) (Double->real x))
              ((instanceof x 'java.lang.Integer) (Integer->integer x))
              (else x)))

(define (box args)
        (map scheme->java args))
(define (unbox args)
        (map java->scheme args))

(define (easy-construct cls . args)
        (apply construct cls (box args)))
(define (easy-invoke obj method . args)
        (java->scheme (apply invoke (scheme->java obj) method (box args))))
(define (easy-invoke-static cls method . args)
        (java->scheme (apply invoke-static cls method (box args))))